# 2 - build Unbound
name: CD 20 Build Unbound Docker Image
   
on:   
  workflow_run:
    workflows: [CD 10 Adguard Home and Unbound check]
    types:
      - completed
  # for testing
  workflow_dispatch:

jobs:
  buildvars:
    # uncomment when not testing
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      BUILD_DATE: ${{ steps.IMPORT_BUILDVARS.outputs.BUILD_DATE }}
      ADGUARDHOME_VERSION: ${{ steps.IMPORT_BUILDVARS.outputs.ADGUARDHOME_VERSION }}
      UNBOUND_DOCKERBUILDENV_VERSION: ${{ steps.IMPORT_BUILDVARS.outputs.UNBOUND_DOCKERBUILDENV_VERSION }}
      DOCKER_IMAGE_VERSION: ${{ steps.IMPORT_BUILDVARS.outputs.DOCKER_IMAGE_VERSION }}
      
    steps:             
    - name: Checkout source
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    
    - name: Import build variables from buildvars file
      id: IMPORT_BUILDVARS
      run: |
        cat buildvars | grep BUILD_DATE >> $GITHUB_OUTPUT
        cat buildvars | grep ADGUARDHOME_VERSION >> $GITHUB_OUTPUT
        cat buildvars | grep UNBOUND_DOCKERBUILDENV_VERSION >> $GITHUB_OUTPUT
        cat buildvars | grep DOCKER_IMAGE_VERSION >> $GITHUB_OUTPUT

  adguard_unbound-build: 
    # uncomment when not testing
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: buildvars
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKERHUB_SLUG: "megavolts/adguard_unbound"
        with:
#          platforms: linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64
#          platforms: linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64
          platforms: linux/armv7,linux/armv6

          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            BUILD_DATE=${{ needs.buildvars.outputs.BUILD_DATE }}  
            ADGUARDHOME_VERSION=${{ needs.buildvars.outputs.ADGUARDHOME_VERSION }}  
            UNBOUND_DOCKERBUILDENV_VERSION=${{ needs.buildvars.outputs.UNBOUND_DOCKERBUILDENV_VERSION }}
            DOCKER_IMAGE_VERSION=${{ needs.buildvars.outputs.DOCKER_IMAGE_VERSION }}
          file: ./adguard_unbound/Dockerfile   
          push: ${{ github.event_name != 'pull_request' }}
          sbom: ${{ github.event_name != 'pull_request' }}
          provenance: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:${{ needs.buildvars.outputs.DOCKER_IMAGE_VERSION }}   
            ${{ env.DOCKERHUB_SLUG }}:latest    